
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'hotel_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'hotel_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  hotel_analytics:
    # Config indicated by + and applies to all files under models/example/

    # RAW layer: sources only (no models built here)
    raw:
      +materialized: table
      +schema: RAW
      +tags: ["raw"]

    # STAGING: clean, standardized tables
    staging:
      +materialized: table
      +schema: STAGING
      +tags: ["staging"]

    # DATAMART: analytics-ready star schema + KPI tables
    marts:
      +materialized: table
      +schema: DATAMART
      +tags: ["mart"]

      # Optional subfolder organization
      core:
        +tags: ["core"]

      metrics:
        +tags: ["metrics"]

# Tests (keep it lightweight for now)
tests:
  hotel_analytics:
    +severity: warn