-- =========================================================
-- Hotel Analytics Platform — Snowflake Landing Zone Setup
-- =========================================================

-- 1) Create database + schemas
CREATE DATABASE IF NOT EXISTS HOTEL_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS HOTEL_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS HOTEL_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS HOTEL_ANALYTICS.DATAMART;

-- 2) File format for CSV / CSV.GZ
CREATE OR REPLACE FILE FORMAT HOTEL_ANALYTICS.RAW.CSV_FMT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE
  ENCODING = 'UTF8'
  COMPRESSION = 'AUTO';

-- 3) Internal stage = landing zone
CREATE OR REPLACE STAGE HOTEL_ANALYTICS.RAW.LANDING_STAGE
  FILE_FORMAT = HOTEL_ANALYTICS.RAW.CSV_FMT;

-- 4) Sanity checks (THIS is where IDENTIFIER() breaks)
DESC STAGE HOTEL_ANALYTICS.RAW.LANDING_STAGE;

LIST @HOTEL_ANALYTICS.RAW.LANDING_STAGE;
